language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

install:
  - "pip install -r requirements.txt"
  - "pip install pexpect flake8"

script:
  - "python -m unittest discover"
  - "./run_linter.sh"
