language: python

matrix:
  include:
    - os: linux
      python: 2.7

    - os: linux
      python: 3.4

    - os: linux
      python: 3.5

    - os: linux
      python: 3.6

    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.13

    - os: osx
      language: generic
      env: PYTHON_VERSION=3.4.6

    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5.3

    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.1

install:
  - "./.travis/install.sh"

script:
  - "./.travis/run.sh"